#!/bin/bash
#get only image from CLI input, without path
x=$1
y=${x%}
image_name=$(echo ${y##*/})
#list all images to file images_list.txt
ls -r *.jpg *.jpeg *.png *.bmp *.gif > /tmp/images_list.txt 2> /dev/null
tac /tmp/images_list.txt > /tmp/images_list_reversed.txt
#Get number of selected image
image_number=$(grep -n $image_name /tmp/images_list_reversed.txt | cut -f1 -d:)
# echo $image_number
#pipe result of image list, starting by displaying the selected image number
cat /tmp/images_list_reversed.txt | sxiv -i -n $image_number
