local options = {
	clipboard = "unnamedplus",
	termguicolors = true,                                    
	synmaxcol = 500,
	regexpengine = 1,
	updatetime = 50,
	number = true,
	showcmd = true,                 
	--noshowmode = true,               
	--noruler = true,                 
	-- statusline = "⠀",  
	matchtime = 3,
	ttimeoutlen = 10,
	tabstop = 2,
	softtabstop = 2,
	shiftwidth = 2,
	smarttab = true,
	shiftround = true,
	--noexpandtab = true,
	backspace = indent,eol,start,
	textwidth = 106,
	autoindent = true,       
	breakindent = true,
	linebreak = true,      
	mouse = "a",
	wildmenu = true,
	wildmode = full,        
	virtualedit = block,
	--nostartofline = true,
	hlsearch = true,
	incsearch = true,
	ignorecase = true,
	smartcase = true,
	confirm = true,
	autowrite = true,
	--complete-=i,  
	--shortmess=atIc,
	pumheight = 10,
	laststatus = 1,
	scrolloff = 2,
	sidescrolloff = 2,
	splitbelow = true,
	splitright = true,
	undofile = true,
	history = 1000,
	backup = true,
	writebackup = true,
	backupcopy = yes,
	undodir = "/home/house/.vim/tmp/undo",
	directory = "/home/house/.vim/tmp/swap",
	backupdir = "/home/house/.vim/tmp/backup",
	dictionary = "/usr/share/dict/words",
	completeopt = { "menuone", "noinsert" },
	hidden = true,
	belloff = all,
	ttyfast = true,
	lazyredraw = true,
}

for k, v in pairs(options) do
	vim.opt[k] = v
end

vim.opt.shortmess:append "atIc"

vim.cmd "set wildcharm=<C-z>"
vim.cmd "set whichwrap+=<,>,[,],h,l"

